config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'

  devise_for :users

  resources :item_groups
  resources :items
  resources :apps

end

app/models/item_group.rb
class ItemGroup < ActiveRecord::Base
end

app/controllers/item_groups_controller.rb
class ItemGroupsController < ApplicationController
  before_action :set_item_group, only: [:show, :edit, :update, :destroy]

  # GET /item_groups
  # GET /item_groups.json
  def index
    @item_groups = ItemGroup.all
  end

  # GET /item_groups/1
  # GET /item_groups/1.json
  def show
  end

  # GET /item_groups/new
  def new
    @item_group = ItemGroup.new
  end

  # GET /item_groups/1/edit
  def edit
  end

  # POST /item_groups
  # POST /item_groups.json
  def create
    @item_group = ItemGroup.new(item_group_params)

    respond_to do |format|
      if @item_group.save
        format.html { redirect_to @item_group, notice: 'Item group was successfully created.' }
        format.json { render :show, status: :created, location: @item_group }
      else
        format.html { render :new }
        format.json { render json: @item_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_groups/1
  # PATCH/PUT /item_groups/1.json
  def update
    respond_to do |format|
      if @item_group.update(item_group_params)
        format.html { redirect_to @item_group, notice: 'Item group was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_group }
      else
        format.html { render :edit }
        format.json { render json: @item_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_groups/1
  # DELETE /item_groups/1.json
  def destroy
    @item_group.destroy
    respond_to do |format|
      format.html { redirect_to item_groups_url, notice: 'Item group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_group
      @item_group = ItemGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_group_params
      params.require(:item_group).permit(:name)
    end
end

app/helpers/item_groups_helper.rb
module ItemGroupsHelper
end

app/views/item_groups/_form.html.erb
<%= form_for(@item_group) do |f| %>
  <% if @item_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_group.errors.count, "error") %> prohibited this item_group from being saved:</h2>

      <ul>
      <% @item_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_groups/edit.html.erb
<h1>Editing Item Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_group %> |
<%= link_to 'Back', item_groups_path %>

app/views/item_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_groups.each do |item_group| %>
      <tr>
        <td><%= item_group.name %></td>
        <td><%= link_to 'Show', item_group %></td>
        <td><%= link_to 'Edit', edit_item_group_path(item_group) %></td>
        <td><%= link_to 'Destroy', item_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item group', new_item_group_path %>

app/views/item_groups/new.html.erb
<h1>New Item Group</h1>

<%= render 'form' %>

<%= link_to 'Back', item_groups_path %>

app/views/item_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_group.name %>
</p>

<%= link_to 'Edit', edit_item_group_path(@item_group) %> |
<%= link_to 'Back', item_groups_path %>