config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'

  devise_for :users

  resources :item_groups
  resources :items
  resources :apps

end

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :store_id %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New App', new_app_path, class: "btn btn-lg btn-default" %>

<div class="row">
  <div class="col-xs-12">
    <div class="text-center">
      <%= paginate @apps %>
    </div>

    <div class="text-right">
      <%= page_entries_info @apps %>
    </div>
  </div>
</div>

<div class="box">
  <% @apps.each do |app| %>
    <%= app.id %>
    <%= app.name %>
    <% if app.banner_url.present? %>
      <%= link_to lazy_image_tag(app.banner_url, class: "hoge"), app.url %>
    <% else %>
      <%= link_to lazy_image_tag(banner_url(app.url), class: "hoge"), app.url %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>アプリ名</th>
          <th>URL</th>
          <th>ストアID</th>
          <th>バナーurl</th>
          <th>アイコン</th>
          <th colspan="3">更新</th>
        </tr>
      </thead>

      <tbody>
        <% @apps.each do |app| %>
        <tr>
          <td><%= app.name %></td>
          <td><%= app.url %></td>
          <td><%= app.store_id %></td>
          <td><%= app.banner_url %></td>
          <% if app.banner_url.present? %>
            <td><%= link_to lazy_image_tag(app.banner_url, class: "hoge"), app.url %></td>
          <% else %>
            <td><%= link_to lazy_image_tag(banner_url(app.url), class: "hoge"), app.url %></td>
          <% end %>
          <td><%= link_to 'Show', app, class: "btn btn-lg btn-default" %></td>
          <td><%= link_to 'Edit', edit_app_path(app), class: "btn btn-lg btn-default" %></td>
          <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-default" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if false %>ここからコメント
<div style="">
<% @apps.each do |app| %>
        <ul class="col-xs-3" style="border: double 2px #0000ff; display: block;">
          <li><%= app[:id] %></li>
          <li><%= app[:name] %></li>
          <li><%= image_tag app[:banner_url], class: "hoge" %></li>
        </ul>
        <% end %>
</div>
ここまでコメント<% end %>

<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>アプリ名</th>
          <th>アイコン</th>
        </tr>
      </thead>
      <tbody>
        <% @apps.each do |app| %>
        <tr>
          <td><%= app[:id] %></td>
          <td><%= app[:name] %></td>
          <td><%= lazy_image_tag app[:banner_url], class: "hoge" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="text-center">
      <%= paginate @apps %>
    </div>
  </div>
</div>

<br>

<%= link_to 'New App', new_app_path, class: "btn btn-lg btn-default" %>

<script type="text/javascript">
$(function(){
  $("img.lazy").lazyload({ effect: 'fadeIn', threshold: '200' });
  console.log('aaaaaaaaa')
});
</script>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @app.url %>
</p>

<p>
  <strong>Store:</strong>
  <%= @app.store_id %>
</p>

<p>
  <strong>Banner url:</strong>
  <%= @app.banner_url %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>